### ISSUE TITLE
Use LDAP as authentication backend

### ISSUE THREAD

**Issue by Glandos** [dennisreimann/masquerade#15]
Hi !
Masquerade seems to be the most promising open-source OpenID server, and it will be wonderful when it can handle authentication through an already existing LDAP.
Do you have any plan to integrate it ?

**Comment by dennisreimann** [comment]
Hey, there is a branch for that and I'd really like to seperate out the authentication methods as strategies, as you can see here: http://github.com/dbloete/masquerade/commit/ab0c11d49b4e313360ada87d395ddb7578c163c0

However, I'm currently not using masquerade in production and don't have the use case for using it with an LDAP backend, but I implemented it for my bachelor thesis and would like to bring it back into master, but I guess I'll work on that after we've ported the app to Rails 3, because we'll most likely switch to using Devise instead of restful_authentication and this will bring some changes with it. Have an eye on this issue but don't expect it to be implemented in the next two weeks.

**Comment by Glandos** [comment]
Ok, thanks for the fast answer! I'm not in a hurry, I'm just investigating for good OpenID servers. Since you already thought about using multiple authentication backend, I don't have doubt it will present in a future version.

**Comment by jimcavoli** [comment]
So...two years later...
Has any work been done on doing this in a production-ready manner? I know it hasn't been merged back into master yet, but I am preparing to do exactly this in production, and if it hasn't been done or worked on, I'd love to toss my changes back at the project.

**Comment by dennisreimann** [comment]
I'd really like to See your take on that and if it's tested properly I'd merge it in.

**Comment by jimcavoli** [comment]
Forked. Be back with news soon

**Comment by jimcavoli** [comment]
# Update

Just as an update on the development process on this, I'm implementing LDAP via a slightly larger cat, the notorious OmniAuth, in an "omniauth" branch. I'll take this time to go ahead and lay out exactly what led to this decision, starting with some of the obviously concerning stuff.

## Why OmniAuth?

Well, several reasons, which I will lay out here:
1. OmniAuth is pretty bomb-proof
- Under continued, active development
- Tested and used in production by thousands of applications
  1. Even full-on OmniAuth won't force any loss in feature support
- OmniAuth ID will provide traditional username/password db auth
- OmniAuth has YubiKey a strategy built in to provide that functionality
  1. OmniAuth is more future-proofed and pro-feature-development, which will make Masquerade a more appealing product
- OmniAuth has an LDAP strategy that is going to drop in much nicer than mine, and be better maintained
- Expanding to do Kerberos, SAML, or another type of supported authentication is going to be a matter or hours, not days/weeks
  1. OmniAuth is lighter-weight
- End-users can choose which provider(s) they want to enable, easily from a config file or hard-coding (haven't decided which route to develop yet)
- New providers are a line or two of code, not entire new classes
- Strategies end-users don't want can be simply excluded using the Gemfile, without leaving lots of overhead in code behind
  1. Masquerade enjoys wider development by proxy
- OmniAuth is a Ruby language-wide applicable gem
- This means there is a community even broader than the vibrant Rails community with an interest in OmniAuth
- More community = more support
- More support = better-made, better-tested, and more frequently updated strategies

## What I'm doing

I'll be refactoring masquerade wherever necessary to make a clean, well-put-together, DRY implementation of OmniAuth authentication. The core functionality for providing OpenIDs is awesome, and I want to keep the accounts model from getting cluttered up with auth fields it won't always utilize. Obviously, pulling in OmniAuth is going to be interesting as using authentication providers to create an authentication provider is a little circular at first glance, and I do want to be careful to not create pointless functionality, but I can envision lots of use cases in which this is more helpful than stupid.

## What it would be nice to have help with

Tests. Yeah, I can definitely get all this stuff in there, and my first goal on the "omniauth" branch is going to be functionality, not writing tests. Also, I've never worked with infinity_test. So I'll look at that later too.
Then there's the ongoing promotion of OpenID as an authentication method. Not sure what any of us will do for this directly, but you know, tell your friends!

## Questions, comments, and poisonous reptiles

I'm definitely in a discussing mood about this, if anyone cares to raise any counter-points or offer any additional insight, so please comment. My development for implementing OmniAuth is going on right now, and it should be functional this week.

**Comment by dennisreimann** [comment]
Hey Jim, I've been thinking about this lately, because some people asked about the state of migrating the authentication to Devise. Switching to Omniauth makes total sense and you explained it very well. Go ahead and involve me, wherever I can provide help.

**Comment by huangye177** [comment]
Hi Jim and Dennis, since I am watching for the masquerade project closely, I'd like to have a understanding in terms of what might be of the output of this fork. 
As Jim stated, "The core functionality for providing OpenIDs is awesome, and I want to keep the accounts model from getting cluttered up with auth fields it won't always utilize." So does it mean the functionality as a "Provider" in Masquerade will be kept somehow as it is. -- I mean, for instance, the Account model & related controller, and the critical server controller will be kept with no major modification.
On the other hand, since for me, the OmniAuth is more about an authentication/authorization framework for "Consumer" applications (those get authenticated information from the Providers to continue their own local processing), the primary output of this fork will focus on the reimplementation of the Consumer code, i.e, the client controller, and maybe the Consumer oriented processing with the Account.
Is my understanding right or I got lost in the vision?

**Comment by jimcavoli** [comment]
Right now, what we're talking about doing is giving the Provider the ability to authenticate users against multiple backends. Relying parties only authenticate against OpenID. You may be confusing OmniAuth with OAuth from the sound of it, which is a common mistake. OpenID = user authentication, OAuth = application authorization. OmniAuth is neither of these things. OmniAuth is a library which wraps up methods of making calls to a number of different services over a number of different protocols, and  sort of bridges both worlds.

[This post](http://softwareas.com/oauth-openid-youre-barking-up-the-wrong-tree-if-you-think-theyre-the-same-thing) does a pretty good job of explaining what I'm trying to get across, and Chris Messina really gets into some good explanation in [this video](http://www.youtube.com/watch?v=3GMfexcYk6U), just a few minutes in.

**Comment by huangye177** [comment]
Hi Jim, thanks for the reply. Unfortunately, I am afraid you answered something different. I have been playing both openID recently and I have a already implemented OAuth solution in my own app, thus I guess the conception understanding is not a problem.
OK, I try to rephrase my question in a working scenario and hope it helps the communication. For now, I have a OAuth solution implemented, wherein the OmniAuth gem is used to implement OAuth Client and the Oauth-Plugin is used to implement the OAuth Provider. The reason of that is, as mentioned above, the OmniAuth is a Client authentication/authorization programming framework (or gem, I do NOT mean it is a protocol) and can only supply the building of a OAuth Client.
Now, the same thing happens in OpenID, I have OpenID Client implemented via AuthLogic (and there are many other gems support building a OpenID Client). On the other hand, to build a OpenID Provider, I choose to use Masquerade instead of starting from scratch with Ruby-OpenID. So, that is what I got up to now:
OpenID Provider: Masquerade
OpenID Client (relying party): AuthLogic (on the way to change into Devise based Client)
OAuth2 Provider: Oauth-Plugin
OAuth2 Consumer: OmniAuth

Now, my question is, what is the output of the newly created gem branch, what is the benefits, or, in another word, which part of my current solution will be changed if I wanna adopt the new gem. Or, where to put the new gem in my current solution?
I think the clarify of the purpose and final output of branch may help the community to understand the work better, and may also encourage users like me to watch and adopt the new gem.

**Comment by jimcavoli** [comment]
Ah, okay, I think I see what you're asking now, @huangye177 - the idea of the "omniauth" branch is to make the Masquerade server an OmniAuth client of the omniauth-identity, omniauth-yubikey, and omniauth-ldap providers so that it can support using a remote user store easily, namely to provide LDAP-based authentication of a user's entered credentials, and potentially SAML and/or CAS down the line.

To address your concerns directly, no part of your current setup would have to change after the upgrade, but rather should you want to log users into Masquerade from an LDAP store rather than the database, you would have the ability to do so.

**Comment by dennisreimann** [comment]
@jimcavoli just to let you know: I started to port over the masquerade code to another project (https://github.com/dbloete/masq), where I try to convert masquerade to a Rails engine. It started out as an experiment yesterday but it seems easier than expected and I think being able to use masquerade as a Rails engine would be a greg thing, as it would give one the opportunity to run it standalone or integrate it into existing apps.

How many progress have you already made with your OmniAuth migration? I think I'll get the masq repo ready next week as the tests are the only bigger part that I haven't ported yet. From what I've seen so far it wouldn't be that big of a deal to port your changes over from masquerade to masq once you are done. My overall goal would be to use masq as the primary platform from after you are done, as it is the more modular approach. What do you think?

**Comment by jimcavoli** [comment]
ooh, good idea. I got slowed down last week on the OmniAuth migration because of some family things, but I have got the basics of it running already, and I'm going to be working on it more tonight. I was hoping to flesh it out this week, do a little feature checking and push it up into that branch publicly by Friday basically complete, save for some testing and group review. It too, has turned out, as it should be, pretty easy to integrate.

I think being able to run masquerade as a rails engine is a great idea.

**Comment by dennisreimann** [comment]
Ok, then let's see where we are at the beginning of the next week, no hurry though :)

**Comment by dennisreimann** [comment]
Alright, as far as I can see porting the app worked out well, the tests are running and I added some notes about how to upgrade an existing masquerade app to masq. It would be nice to get some feedback on that and if someone would like to help with shaping the rough edges (like creating a migration for renaming the old tables) and improving the upgrade docs.

**Comment by dennisreimann** [comment]
@jimcavoli just wanted to ask about the state of your fork. can I provide help?

**Comment by dennisreimann** [comment]
@jimcavoli ?

**Comment by dennisreimann** [comment]
Ok, I'll close this one now, as it should get worked on on [masq](https://github.com/dbloete/masq) from now on.
